library(diffusionMap)
library(rdist)
library(readr)
library(rgl)
BCD<-read_csv("desktop/BCD.csv")
colnames(BCD) <- c("id", "diagnosis","radius_mean","texture_mean","perimeter_mean","area_mean","smoothness_mean","compactness_mean","concavity_mean","concave points_mean","symmetry_mean","fractal_dimension_mean","radius_se","texture_se","perimeter_se","area_se","smoothness_se","compactness_se","concavity_se","concave points_se","symmetry_se","fractal_dimension_se","radius_worst","texture_worst","perimeter_worst","area_worst","smoothness_worst","compactness_worst","concavity_worst","concave points_worst","symmetry_worst","fractal_dimension_worst")
dis <- rdist(BCD, metric = "hamming")
dif <- diffuse(dis, neigen = 35)
plot3d(dif$X[,3:32],xlab = "Diffusion Wisconsin",ylab="",zlab = "")
BCC <- read.csv(file="desktop/BCC.csv", sep=",")
dis <- rdist(BCC, metric = "hamming")
dif <- diffuse(dis, neigen = 15)
plot3d(dif$X[,2:9],xlab = "Diffusion Coimbra",ylab="",zlab = "")

